import { Decision, DecisionReason } from "@/modules/address-dedup/constants";
import type { AnalysisRow } from "@/modules/address-dedup/types";

export function makeRow(overrides: Partial<AnalysisRow> = {}): AnalysisRow {
  return {
    group_id: 1,
    fuente: "ANTEL",
    urn: "cgeo:Antel:address:id:1",
    province: "FLORES",
    locality: null,
    street_name: null,
    street_number: "0",
    letter: null,
    square: null,
    sandlot: null,
    km: null,
    padron: "4053",
    type_padron: "RURAL",
    postal_code: "85000",
    lat: -33.461795,
    lng: -56.730707,
    document_type: "PARENT",
    matched_serv_cto_tlk: false,
    matched_nap_physical_device: false,
    has_internal_units: false,
    dup_group_size: 2,
    n_matched_in_group: 0,
    pool_rank_in_group: 1,
    decision: Decision.KEEP,
    decision_reason: DecisionReason.LOWEST_URN_KEPT,
    block: null,
    tower: null,
    floor: null,
    unit: null,
    code_country: null,
    name_country: null,
    id_province: 7,
    raw_rs_censal_locality_name: null,
    raw_rs_censal_locality_code: null,
    rs_cadastral_locality_name: null,
    rs_idcalle: null,
    raw_rs_name: null,
    rs_reftramo: null,
    rs_short_name: null,
    raw_number: "0",
    side: null,
    raw_padron_number: "4053",
    province_code: "UY-FL",
    padron_locality: null,
    padron_locality_or_geo: "GEO:-33.46,-56.73",
    match_key: "FLORES|UY-FL|||85000|GEO:-33.46,-56.73|NONE|NONE|NONE|NONE|NONE|NONE|4053|RURAL|NONE",
    ...overrides,
  };
}
